### ISSUE TITLE
Different display type - Plugin or fork?

### ISSUE THREAD

**Issue by AidanConnelly** [fr3ts0n/AndrOBD#135]
Hi

I'm looking to make a new display output type, rather than a dial or a chart I'm looking to make simple fixed-width text.

What would be the easier method of developing this? Forking the project, or developing a plugin?

**Is your feature request related to a problem? Please describe.**
I can't vary the font size of the stock output types

**Describe the solution you'd like**
To have a large font size on an output type

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by fr3ts0n** [comment]
Hi,
Since this is about a live screen display, it probably makes most sense to fork the project and create a derived: 
* Layout from **obd_item** layout (definition how to display an OBD item)
* Display adapter from **ObdItemAdapter** (to render the item data)

That should pretty much do the job :smiley:
