### ISSUE TITLE
How to get these spies or signal from ELM327

### ISSUE THREAD

**Issue by cristo1985** [fr3ts0n/AndrOBD#140]
Hi, how can i get the code in android db?
1) 0x1E Turn Signal Status
Return Value of 0 = Turn Signal Off
Return Value of 1 = Left Turn On
Return Value of 2 = Right Turn On
Return Value of 3 = Both Signals On
NOTE: On some vehicles the turn signal reports on and off periodically as the signal flashes. Polling may have to be done more frequently from the Streamer to catch the changing signal ...??????
2)  0x0D Battery Voltage
3) 0x00 Vehicle Speed
4) 0x22 Trip Odometer
5) brake, oil etc etc? 
Thanks for any help!

**Comment by fr3ts0n** [comment]
Hi @cristo1985 ,

These ID's you listed are definitely not OBD PID's! 
The mentioned adapter (OBDII-Streamer) does support reading some OEM-specific data for some US vehicles, but creates it's own, specific data item mapping, which is far off from OBD2 standard.

You'll find OBD supported PID's here:
https://en.wikipedia.org/wiki/OBD-II_PIDs

Signals like turn-, brake status etc. usually are transported on the same vehicle bus, but in a vehicle specific format rather than standard OBD. Since each manufacturer uses different communication parameters/patterns for this it is a really hard task to reverse engineer these patterns for each vehicle.
