### ISSUE TITLE
Select adapter menu | Favourites option

### ISSUE THREAD

**Issue by aha999** [fr3ts0n/AndrOBD#200]
**Is your feature request related to a problem? Please describe.**
Currently in Select adapter menu there can be a lot of devices that users have previously connected with... So they have to search and maybe scroll to find one adapter that they will use each time, or if they have more adapters. It is annoying and not time-saving to have to search them among a lot of options.

**Describe the solution you'd like**
Add a Favourites option (if you hold your finger on a device, it would bring a small menu that would say "favourite" so it would put it to favourites at the top.

**Describe alternatives you've considered**
Maybe other options of favouriting the device can be better, but this feature would in any case certainly be nice.

Example:

<img src="https://user-images.githubusercontent.com/50620416/164506101-7c5e5ca9-13cb-4bfa-a0d2-e1e9fac7c2b3.png" width="200">

**Comment by fr3ts0n** [comment]
I have added a wiki page to describe the feature of automatic re-usage of previous selections.
[Automation on statup](https://github.com/fr3ts0n/AndrOBD/wiki/Automation-on-startup)

As mentioned in the wiki, this is the most flexible solution, and even more comfortable for the major group of users, since there are not that many of them switching between multiple adapters.
