### ISSUE TITLE
Local AndrOBD DTC database

### ISSUE THREAD

**Issue by aha999** [fr3ts0n/AndrOBD#202]
**Is your feature request related to a problem? Please describe.**
Currently looking for DTC's depends on the online connection, and information from different websites, which contain a lot of ads, and it is currently not possible to get this information locally.

**Describe the solution you'd like**
Create a Diagnostic Trouble Code repo, where anyone can contribute to, so a local DTC database can be created for AndrOBD.

**Describe alternatives you've considered**
This information be done as a Plugin, or built inside the app. Internet lookup (like currently) could still be available optionally as a toggle option.

**Additional context**
This would make AndrOBD more independent from other websites information and community could help with repo information.
Some information can be found here: https://github.com/todrobbins/dtcdb 
[dtc_list.pdf](https://github.com/fr3ts0n/AndrOBD/files/8582537/dtc_list.pdf) from [this website](https://www.dmv.de.gov/services/Vehicle_Services/dtc_list.pdf).

**Comment by fr3ts0n** [comment]
There is a DTC database in AndrOBD:  [codes.properties](https://github.com/fr3ts0n/AndrOBD/blob/master/library/src/main/java/com/fr3ts0n/ecu/prot/obd/res/codes.properties)

This file maps the OBD DTC codes to the translatable, meaningful text.

The effort of maintenance of such a database of DTC explanations, and the needed detailled expert knowledge/experience should not be under-estimated. It takes a lot of expertise to maintain such a database.

Since there are multiple pages online, which explain DFC causes even type / model specific, i still think it is most effective to use this resource and just do a global lookup in the internet. The user then has the choice to select the preferred match rather than a fixed, prepared enty.
