### ISSUE TITLE
Please use F-Droid for test releases instead of Telegram

### ISSUE THREAD

**Issue by ieffuie4** [fr3ts0n/AndrOBD#267]
**Is your feature request related to a problem? Please describe.**
Its sad to see any sort of advertisement for the telegram company in project that create free as in freedom code. Telegram does exactly the opposite. I have spend over an hour reading and learning about the company in the hope i could download the test build here: https://github.com/fr3ts0n/AndrOBD/issues/241#issuecomment-2223362355
Now i know, that when you for example try to use a free and open source software telegram-app to register there, then you get blocked. You are forced by the telegram company to use their closed source software to register and have to send a phone number to russia/emirates.

**Describe the solution you'd like**
Please do not release/advertise telegram. Instead to release test builds, please use the already existing F-Droid test builds functionality.
AndrOBD is awesome to be only released on F-Droid. It would make much sense to use all the functionality of F-Droid when its needed in a project. And there is need for test builds. So lets use F-Droid for this too. The "Suggested" tag is the one that is used for this. Here you can see it in active use at the moment: https://f-droid.org/en/packages/net.osmand.plus/
The F-Droid developers also use it on their app when there is a test version. Currently there is just the latest stable and that is now also the suggested version: https://f-droid.org/packages/org.fdroid.fdroid/

**Describe alternatives you've considered**
As alternative put the APK on some web-server that can be visited by everyone. But then you loose all the great benefits of F-Droid like public build service and a real simple way to test the builds.

**Comment by fr3ts0n** [comment]
I do not want to use f-droid for beta releases since I will have to manually maintain the f-droid metadata for each release (regular and beta) after the change.
Too much manual work, too much chances to fail ...

I changed to use the github build action to generate unsigned beta packages for download.
here is the first GitHub generated beta package of V2.7.0 test version for download:
https://github.com/fr3ts0n/AndrOBD/actions/runs/9921537206/artifacts/1698194564
