### ISSUE TITLE
Enable Hebrew translation in Weblate

### ISSUE THREAD

**Issue by yarons** [fr3ts0n/AndrOBD#30]
Awesome project, can I pitch in?

Thanks!

**Comment by fr3ts0n** [comment]
You can just start a new translation for hebrew language on weblate.org.
You just have to register as a weblate user for this.
There is nothing I have to enable for that.

Thank you for joining the team :)

**Comment by yarons** [comment]
Are you completely sure about that? Because I'm already registered and I couldn't add Hebrew to the list, should I try and contact Michal?

**Comment by fr3ts0n** [comment]
I have just added the translations for hebrew to the weblate project.
* Strings
* Fault code list
* Data descriptions

I'm not sure why you havent been able to do this, since other people did this for other languages before.
I just logged in and added a new translation at the bottom of the language list.

However, now the hebrew translation is available and ready for you to start :)
