### ISSUE TITLE
Provide a way to stream data to MQTT

### ISSUE THREAD

**Issue by greylurk** [fr3ts0n/AndrOBD#39]
I use HomeAssistant (http://hass.io) pretty extensively, and I'm looking for a way to get my fuel efficiency, mileage, and the like to appear on my HomeAssistant dashboard.  The simplest way would be if I could use AndrOBD to stream that information to an MQTT endpoint, which could then be picked up by HomeAssistant

**Comment by fr3ts0n** [comment]
Sounds like an idea. OBD meets IOT ...

I probably would create some kind of a add on / plugin to AndrOBD since I like to keep the plain AndrOBD rather small.

Do you have any idea of what would need to be configurable?
* MQTT connection 
  - server / login / encryption parameters / ?
* data items to be transfered
* frequency of data updates
  - per data item?
* mapping OBD item to MQTT item
  - fixed / configurable?

**Comment by mueller-ma** [comment]
Hey, that sounds like a good idea. I'm using openHAB and would also like to see such a feature.

    MQTT connection
        server / login / encryption parameters / ?
openHAB has a rest api where you can change items via http post calls. Might this be easier to implement? And is that also possible with HomeAssistant?



    data items to be transfered
All?


    mapping OBD item to MQTT item
        fixed / configurable?
I would say configurable prefix and sufix. Imagine you had to type in the app names for 50 items.
Example: Fuell in % is FUELL_PERCENT
Than you can add CAR1_ as prefix => CAR1_FUELL_PERCENT

**Comment by greylurk** [comment]
If we're doing a plugin, then both the REST and MQTT connectors could be different plugins, but yeah, HomeAssistant can have HTTP/REST based sensors too: 

https://home-assistant.io/components/sensor.http/

However, somewhat annoyingly, the http sensor for HomeAssistant can only accept a single data point at a time, which means if you've got 50 items you're sending, that's 50 requests.  

I think a "fixed" mapping would work for HomeAssistant, since HA has a lot of good tools for mapping/renaming incoming sensors internally. I can't comment on OpenHAB. 

http://mylifewithandroid.blogspot.com/2010/06/plugins.html has an interesting idea for writing plugins for Android apps. I'm still grokking the architecture of AndrODB, but I think that would work?

**Comment by mueller-ma** [comment]
> I think a "fixed" mapping would work for HomeAssistant

Also for openHAB, but only for one car.

**Comment by fr3ts0n** [comment]
Thanks for the links. I'll look into that.

I'd prefer a MQTT publisher client since it is definitely more of a standard than adapting to any specific REST interfaces.
This would need to allow prefix configuration, since the base path of MQTT variables needs to be adjustable anyways.

## About data update rates:
Best case on a single data item AndrOBD could deliver data updates every approx. 5 ms. 
I don't think every OBD data update should be forwarded to the MQTT server.
Easiest option would be to configure one single update interval (like every 30s) which then delivers all selected OBD readings to the MQTT server?
This again leaves additional options:
* send most current value only?
* average values during update period?

**Comment by greylurk** [comment]
30s sounds reasonable to me, though you might even push it out longer.  MQTT is pretty light-weight, but since these updates will presumably be going out on your data plan, sending even 10k every 30 seconds can add up quickly.  Possibly make the timing granularity configurable, or just 2-3 levels: Frequent (every 30s), Occasional (every 5m), Rare (only when the drive starts and ends)
 
As for the value to send, I think averaging sounds right, but there might be cases where "latest" value would be more appropriate, such fuel tank level.

**Comment by mueller-ma** [comment]
I use AndrOBD on my normal smartphone, so sending information once when connecting would be ok for. And only when I'm on my wifi.

**Comment by fr3ts0n** [comment]
I created a [Feature description](https://github.com/fr3ts0n/AndrOBD/wiki/AndrOBD-MQTT-publisher#androbd-mqtt-publisher) to create an overview of this possible extension.

Please have a look and comment if this description does match your vision ...

**Comment by elloza** [comment]
Hello everyone!

I see that feature great! I can collaborate in order to develop it if you want!

Seeing your feature description It seems that you want this feature as a separated apk with a AIDL service and an Activity for setting the configuration parameters separately.

In AndrOBD set only a new setting in order to start the service and stop it.
Regarding to "It shall be possible to trigger a publication manually." this is from AndrOBD, isn't it?

Best regards!

**Comment by fr3ts0n** [comment]
Hi @elloza 

Thanks for the offer to help.

I'd appreciate to get some help with this.

I am currently in progress of writing a design description for a generic AndrOBD extension plugin interface. That also contains the part on manual trigger the publication. (Yes you are correct, it's to be triggered from the AndrOBD side).
I hope to get this to a readable shape before xmas.
 
After that is available, the AndrOBD sided plugin handler and all kinds of plugins can be implemented ...

If you're interested to help on the project, just come and join the [AndrOBD development channel](https://t.me/AndrOBD_dev) on Telegram.

Thx
fr3ts0n

**Comment by fr3ts0n** [comment]
Here is the promised design for extension plugins:
https://github.com/fr3ts0n/AndrOBD/wiki/Design:---AndrOBD-extension-plugin-framework

At least I got it done in the old year ... :smiley:

**Comment by fr3ts0n** [comment]
Initial test implementation apk's are available on [Telegram: AndrOBD dev channel](https://t.me/AndrOBD_dev)

AndrOBD Development branch for plugin framework is: "plugin"
Plugin development repo: [AndrOBD-Plugin](https://github.com/fr3ts0n/AndrOBD-Plugin)

**Comment by fr3ts0n** [comment]
Integrated to master branch now.
Will be released with V2.0.0

Plugin development repo: [AndrOBD-Plugin](../../AndrOBD-Plugin)
MQTT-Publisher plugin module: [MqttPublisher](../../AndrOBD-Plugin/tree/master/MqttPublisher)

will be available on F-Droid soon.

Beta .apk's are available on [Telegram: AndrOBD dev channel](https://t.me/AndrOBD_dev)

Happy testing :smiley:

**Comment by fr3ts0n** [comment]
Delivered on F-Droid with:
* AndrOBD V2.0.2
* MQTT Publisher V1.0
