### ISSUE TITLE
Get all data from OBD

### ISSUE THREAD

**Issue by smartes** [fr3ts0n/AndrOBD#49]
Hi!
I have a question about your program. Actually? I want to get data not from engine, but but from steering wheel. I want to use "forward" "back" "volume" buttons to control my android player. So my idea to get experimentally "who"  is bottom  and program player. So, the question is how to get row of the OBD data (probably all). I have some experience in programming on C but no any for android.  Maybe I can use some of files as template to get all OBD conversations and, probably, guess who is who?

**Comment by fr3ts0n** [comment]
Hi @smartes ,
the media button signal is definitely not part of the OBD diagnostic protocol. 
What you want to do is to sniff into the normal vehicle network communication and find the right message to be filtered and reacted on.

As you already mentioned this will be a serious research job to find the correct CAN message and -bits within the vehicle network. It may even not be available on the OBD connector, since some networks are switched through gateways.

A good start could be a ELM adapter and a terminal program. 
The adapter can be set to monitoring mode which dumps all messages which are visible on the OBD (just with a short time buffering)

Please have a look for the ELM327 documentation to learn the commands for data monitoring.
 
Another interesting project for you to look at is @openxc. 
I think they have some projects going which use sniffed network data.

Good luck
