### ISSUE TITLE
Hex code of turn signals

### ISSUE THREAD

**Issue by novsub** [fr3ts0n/AndrOBD#66]
Hello, as part of a project I need to recover the hex code corresponding to turn signals. Do you have an idea ?
I try to display all hexadecimal codes with turning signals and then without to find them, but I am confronted with the error "buffer full" and I can not increase the amount of bauds.
Thank you in advance !

**Comment by fr3ts0n** [comment]
Hi, 
what you are asking for is neither OBD / nor manufacturer diagnostics protocol (i.e. UDS).

This is about spoofing messages between ECUs on the vehicle network.
Since these messages are not standardized, I can not really give you any hint except using the message filter for the elm monitoring function. (see ELM manual)

Good luck
