### ISSUE TITLE
Feature request: Add to Play Store

### ISSUE THREAD

**Issue by user8446** [fr3ts0n/AndrOBD#84]
Hello,
AndrOBD is a great a lightweight app. Publishing on the Play Store would expose it to users that aren't familiar with side loading or alternate app stores such as FDroid. Are there reasons that it isn't published there?
Thank you for the development!

**Comment by fr3ts0n** [comment]
Hi @user8446 
You are correct,this would broaden the market for AndrOBD considerably.
- Since the clients would be a) more, b) with less technical knowledge, this would also mean to increase the 1st level support drastically.
- On any structural change of the project, the overhead effort for release preparation, is quite something to be considered. This is per release platform. 
- I like to support open source projects, which F-Droid is, and supports.

Since I am operating this as a spare time project, I think it is currently is enough to publish on F-Droid only.

**Comment by user8446** [comment]
That makes perfect sense. Thank you again!
